example:
  kafka: <%= ENV.fetch('KAFKA_URL', '127.0.0.1:9092') %>
  group_id: example-group
  topics:
    - example-topic-1
    - example-topic-2
  keys:
    - example-key-1
    - example-key-2

lot_created:
  kafka: <%= ENV.fetch('KAFKA_URL', '127.0.0.1:9092') %>
  group_id: lot_creator-group
  topics:
    - lot_creator-topic
  # If empty it will consume all messages from topic.
  keys:

bid_created:
  kafka: <%= ENV.fetch('KAFKA_URL', '127.0.0.1:9092') %>
  group_id: bid_creator-group
  topics:
    - bid_creator-topic
  keys:
